#!/bin/bash

set -e

# Update pip
python -m pip install --upgrade pip setuptools wheel

# Install dependencies
python -m pip install .

# Display installed versions
python -V
jupyter --version
python -m pip list

# Install NLTK corpora and tokenizers
python -m nltk.downloader punkt stopwords
